### ISSUE TITLE
get_latest_vagrant_version.rb when vagrantup.com is down 

### ISSUE THREAD

**Issue by ghost** [unibet/puppet-vagrant#3]
Today vagrantup.com was returning 520 errors because their backend was not working properly. 

```
Error: 520 Origin Error at /puppet/dev/modules/vagrant/manifests/params.pp:11 on node test.localdomain
```

As I specify vagrant's version manually, I don't really care if I don't get the latest version. Therefore, I was tempted to add code to only parse answer when HTTP answer is 200. 

```
module Puppet::Parser::Functions
  newfunction(:get_latest_vagrant_version, :type => :rvalue) do |args|
    # tags = JSON.parse(open('https://api.github.com/repos/mitchellh/vagrant/tags') { |u| u.read })
    # tags.sort_by { |tag| tag['name'] }.last['name'][1..-1]
    response = Net::HTTP.get_response(URI.parse('http://www.vagrantup.com/latest-version.json'))
    if response.code == 200
      JSON.parse(response.body { |u| u.read })["version"]
    end

  end
end
```

I'm not sure if this change is useful for the future, but at least it helped me today ;-) 
Keep up the good work!

**Comment by jlyheden** [comment]
Thanks for reporting the issue, setting $version to something like undef in params.pp would probably fix it also since it now gets called needlessly even if you pin the version. I'll fix it, run some tests and push the fix version to the forge

**Comment by i11** [comment]
can we close this? seems like it was fixed.

**Comment by ghost** [comment]
Good for me
