### ISSUE TITLE
Latest version no longer available from vagrant website

### ISSUE THREAD

**Issue by cpick** [unibet/puppet-vagrant#8]
Currently, if the `vagrant` class (or, really, the `vagrant::package` resource) isn't explicitly provided a version number, `get_latest_vagrant_version()` tries to query http://www.vagrantup.com/latest-version.json to determine the latest verison.

Unfortunately, that URL now 404s.  Apparently, upstream vagrant removed its use of that URL back in https://github.com/mitchellh/vagrant/commit/140a1b8d4b78f06d630b21bb31ba8d690e4bfe5e in 2014-09 and they've decided to retire it.

**Comment by razorsedge** [comment]
Use the [hashicorp-checkpoint](https://rubygems.org/gems/hashicorp-checkpoint) gem to query the HashiCorp [Checkpoint service](https://checkpoint.hashicorp.com) to determine latest version.

**Comment by razorsedge** [comment]
See the output of:
https://checkpoint-api.hashicorp.com/v1/check/vagrant?version=1.8.0&arch=amd64&os=linux-gnu
vs
https://checkpoint-api.hashicorp.com/v1/check/vagrant?version=1.8.1&arch=amd64&os=linux-gnu

**Comment by jlyheden** [comment]
I would rather not add a gem dependency here, in particular since functions are evaluated during the catalog compilation phase (would mean that the gem would have to be installed on the master in an agent setup). I'll reverse engineer the gem when I have time to extract the calls it makes.

**Comment by jlyheden** [comment]
Hmm you already did that more or less @razorsedge :)

**Comment by jlyheden** [comment]
Released version 0.2.1
